export const SET_TOKEN = 'SET_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

export const SHOW_MODAL_LOGOUT = 'SHOW_MODAL_LOGOUT';
export const HIDE_MODAL_LOGOUT = 'HIDE_MODAL_LOGOUT';

export const SHOW_MODAL_INFO = 'SHOW_MODAL_INFO';
export const HIDE_MODAL_INFO = 'HIDE_MODAL_INFO';

export const SHOW_MODAL_GLOB = 'SHOW_MODAL_GLOBAL';
export const HIDE_MODAL_GLOB = 'HIDE_MODAL_GLOBAL';

export const START_REQUEST = 'START_REQUEST';
export const END_REQUEST = 'END_REQUEST';
export const ERROR_REQUEST = 'ERROR_REQUEST';
export const REGISTRATION_SUCCESSFULL = 'REGISTER'; 
export const REGISTRATION_FAILURE = 'REGISTER_FAIL'; 

export const SAVE_LOCAL_STORAGE = 'SAVE_LOCAL_STORAGE';

export const SET_INIT_TASKLIST = 'SET_TASKlIST'; 
export const SET_TASK_OPTIONS = 'SET_TASK_OPTIONS';
export const SET_TASK_FOR_CHANGE = 'SET_TASK_FOR_CHANGE';

export const SET_MARK_OF_AUTO_LIST = 'SET_AUTOS_LIST';
export const SET_MODEL_BY_MARK = 'SET_MARK';
export const SET_CURRENT_MODEL = 'SET_CURRENT_MODEL'
export const SET_CURRENT_MARK = 'SET_CURRENT_MARK'

export const SET_FINAL_TASK = 'SET_FINAL_TASK';

export const SEND_FINAL_TASKS = 'SEND_FINAL_TASKS';

export const GET_DONE_TASKS = 'GET_DONE_TASKS';

///HISTORY_Modal

export const H_SET_MARK = 'H_SET_MARK';
export const H_SET_MODEL = 'H_SET_MODEL';
export const H_SET_DATE = 'H_SET_DATE';
export const H_SET_TITLE = 'H_SET_TITLE';
export const H_SET_COST = 'H_SET_COST';
export const H_SET_SIDE = 'H_SET_SIDE';
export const H_SET_SUBWORK = 'H_SET_SUBWORK';
export const H_ADD_TASK = 'H_ADD_TASK'; 
export const H_ADD_SUBWORK = 'H_ADD_SUBWORK';
export const H_ADD_SIDE = 'H_ADD_SIDE';
export const H_DELETE_SUBWORK = 'H_DELETE_SUBWORK';
export const H_DELETE_TASK = 'H_DELETE_TASK';
export const H_DELETE_SIDE = 'H_DELETE_SIDE';
export const H_DELETE_ORDER = 'H_DELETE_ORDER';
export const H_UPDATE_RESP = 'H_UPDATE_RESP';
export const H_SET_FETCHING = 'SET_FETCHING_HISTORY';

export const H_D_SET_DETAILS = 'H_D_SET_DETAILS';

//USER
export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_FETCHING = 'USER_FETCHING';
export const SET_UPDATED_USER_INFO = 'SET_UPDATED_USER_INFO'

//COMMON 

export const SET_TASK_MENU_TITLE = 'SET_TASK_MENU_TITLE';